apiVersion: v1
kind: Service
metadata:
  name: atomic
spec:
  ports:
  - port: 1880
    targetPort: 1880
  selector:
    app: atomic

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atomic
spec:
  serviceName: atomic
  replicas: 1
  selector:
    matchLabels:
      app: atomic
  template:
    metadata:
      labels:
        app: atomic
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      initContainers:
      - name: clear-assets
        image: alpine:latest
        command: 
          - sh
          - -c
          - |
            rm -rf /assets/*
            rm -rf /assets/.* || true
        volumeMounts:
          - name: atomic-assets
            mountPath: "/assets"
      - name: clone-assets
        image: alpine/git
        command: ["git", "clone", "https://github.com/BrobridgeOrg/gravity-k8s.git", "/assets"]
        volumeMounts:
          - name: atomic-assets
            mountPath: "/assets"
      containers:
      - name: atomic
        image: "brobridgehub/atomic-labdemo:v0.0.5-20230413-01"
        ports:
        - containerPort: 1880
        env:
        - name: TARGET_TESTDB_READY_FILE
          value: /e2e_status/.target_testdb_ready
        volumeMounts:
        - name: atomic-volume
          mountPath: /data/atomic
        - name: e2e-status-volume
          mountPath: /e2e_status
        command: ["/bin/sh", "-c"]
        args: 
        - |
          # echo "Waiting for target E2Etest DB to be ready"
          # while [ ! -f $$TARGET_TESTDB_READY_FILE ]; do
          #   echo "Waiting for target E2Etest DB to be ready"
          #   sleep 1
          # done
          npm start --cache /data/atomic/.npm -- --userDir /assets/assets/atomic-flow /assets/assets/atomic-flow/flows.json
  volumeClaimTemplates:
  - metadata:
      name: atomic-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: e2e-status-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: atomic-assets
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
