apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gravity-dispatcher
spec:
  serviceName: gravity-dispatcher
  replicas: 1
  selector:
    matchLabels:
      app: gravity-dispatcher
  template:
    metadata:
      labels:
        app: gravity-dispatcher
    spec:
      initContainers:
        - name: clone-assets
          image: alpine/git
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              rm -rf /assets/*
              rm -rf /assets/.[!.]* || true
              cd /assets
              git config --global init.defaultBranch main
              git init
              git remote add origin https://github.com/BrobridgeOrg/gravity-k8s.git
              git config core.sparseCheckout true
              echo "assets/dispatcher" >> .git/info/sparse-checkout
              git pull --set-upstream origin main

          volumeMounts:
            - name: dispatcher-assets-pvc
              mountPath: "/assets"
      containers:
        - name: gravity-dispatcher
          image: brobridgehub/gravity-dispatcher:v0.0.4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              until wget -qO- nats-jetstream.default.svc.cluster.local:8222/healthz | grep -qi "ok"; do
                echo "Waiting for nats-jetstream:8222 to be ready"
                sleep 1;
              done
              echo "Start gravity-dispatcher"
              /gravity-dispatcher &
              pid=$$!
              sleep 2
              /assets/assets/dispatcher/create_product.sh
              if [ $$? -ne 0 ]; then
                echo "@@ Failed to create product !!!"
              else
                echo "## Product has been created. Waiting for gravity-dispatcher(pid $$pid) to terminate."
              fi
              wait $$pid
          volumeMounts:
            - name: dispatcher-assets-pvc
              mountPath: /assets
          env:
            - name: GRAVITY_DISPATCHER_GRAVITY_HOST
              value: nats-jetstream.default.svc.cluster.local
            - name: GRAVITY_DISPATCHER_GRAVITY_PORT
              value: "32803"
  volumeClaimTemplates:
  - metadata:
      name: dispatcher-assets-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
